name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-linux:
    name: Build linux version
    runs-on: ubuntu-latest
    container: python:3.11
    outputs:
      should-run-coverage: ${{ steps.check-execute.outputs.should_run_coverage }}
      should-run-increase: ${{ steps.check-execute.outputs.should_run_increase }}
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          pip install poetry
          poetry install
      - name: build installer
        run: poetry run pyinstaller installer/linux_installer.py
      - name: build native messaging host
        run: poetry run pyinstaller native-messaging-host/e-ra-helper.py
      - name: make dist folder
        run: |
          mkdir linux
          mv dist/e-ra-helper/e-ra-helper linux/e-ra-helper
          mv dist/linux_installer/linux_installer linux/linux_installer
          mv native-messaging-host/com.eoh.era_helper_desktop.json linux/com.eoh.era_helper_desktop.json
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: linux/

  build-window:
    name: Build window version
    runs-on: windows-latest
    outputs:
      should-run-coverage: ${{ steps.check-execute.outputs.should_run_coverage }}
      should-run-increase: ${{ steps.check-execute.outputs.should_run_increase }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install dependencies
        run: |
          pip install poetry
          poetry install
      - name: build installer
        run: poetry run pyinstaller installer/window_installer.py
      - name: build native messaging host
        run: poetry run pyinstaller native-messaging-host/e-ra-helper.py
      - name: make dist folder
        run: |
          mkdir window
          mv dist/e-ra-helper/e-ra-helper.exe window/e-ra-helper.exe
          mv dist/window_installer/window_installer.exe window/window_installer.exe
          mv native-messaging-host/com.eoh.era_helper_desktop.json window/com.eoh.era_helper_desktop.json
      - uses: actions/upload-artifact@v3
        with:
          name: window
          path: window/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-window
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: window
      - uses: actions/download-artifact@v3
        with:
          name: linux
      - name: list files
        run: ls -al
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            window.zip
            linux.zip